before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-dev openssl libssl-dev libevent-dev git

install: bootstrap.py

#language: python
#matrix:
#  include:
#    - python: "2.7"
#      env: TEST_SUITE=suite_2_7

